config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
    @url = "https://maps.googleapis.com/maps/api/staticmap?center=#{@flat.address}&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY"
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-4">

      <div class="flat-card">

        <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>

        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4>Light &amp; <%= flat.name %></h4>
          </div>
          <p><%= flat.address %></p>
          <div class="flex">
            <div class="flex-item">
              <i class="fas fa-users"></i><%= flat.number_of_guests %>
            </div>
            <div class="flex-item">
              <i class="fa fa-euro-sign"></i><%= flat.price_per_night %>
            </div>
          </div>
        </div>

        <div class="flat-card-actions">
          <%= link_to "More info", flat_path(flat)%>
          <a href="#" class="ml-3 text-warning">Edit</a>
          <a href="#" class="ml-3 text-danger">Remove</a>
        </div>

      </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>
<div class="col-xs-6">
<%= render 'form', flat: @flat %>


<%= link_to 'Back', flats_path %>
</div>

app/views/flats/show.html.erb
<div style=" width: 100%; height: 400px; background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200');">
  </div>


  <div style=" width: 100%; height: 400px; background-image: url(@url);"></div>

app/views/layouts/_navbar.html.erb
<nav class="navbar-airbnb">
  <h1>Simple Airbnb</h1>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ml-auto flex">

      <%= link_to "Add a flat", new_flat_path(@flat), class: "btn btn-primary" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- [...] -->
</head>

<body>
  <%= render '/layouts/navbar'%>
  <%= yield %>
</body>
</html>